### ISSUE TITLE
Error in using GUI

### ISSUE THREAD

**Issue by 7Fallen7** [YuanyueLi/EntropySearch#4]
Error "Software is busy, connecting to the backend ......" when opening the GUI.Is this problem related to the fact that my OS is win11?
![36f3260adfa2396f51736036e7914bf](https://github.com/YuanyueLi/EntropySearch/assets/113542182/13852e6d-24ad-4a53-a48f-889fc237db44)

**Comment by YuanyueLi** [comment]
The Flash Entropy Search should work in Windows 11. When you execute the program, it will start a GUI (what you saw) and a backend program to perform the library search. This error happens when:

1. The port (8711) which the GUI and the backend communicate with, has been occupied by another program.
2. The backend fails to start due to some unknown reason like antivirus or system configuration.

I will take a look at this problem and find a solution for it.

**Comment by YuanyueLi** [comment]
Hi, 

The latest version v2.0.1 should fix this problem, you can try this one: [https://github.com/YuanyueLi/EntropySearch/releases](https://github.com/YuanyueLi/EntropySearch/releases)
If the problem continues to exist, feel free to let me know.
